# coding: utf-8

"""
    mParticle

    mParticle Event API

    OpenAPI spec version: 1.0.1
    Contact: support@mparticle.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import mparticle
from mparticle.rest import ApiException
from mparticle.apis.events_api import EventsApi


class TestEventsApi(unittest.TestCase):
    """ EventsApi unit test stubs """

    def setUp(self):
        self.api = mparticle.apis.events_api.EventsApi()

    def tearDown(self):
        pass

    def test_bulk_upload_events(self):
        """
        Test case for bulk_upload_events

        Send events to mParticle
        """
        pass

    def test_upload_events(self):
        """
        Test case for upload_events

        Send events to mParticle
        """
        pass


if __name__ == '__main__':
    unittest.main()
