# coding: utf-8

"""
    mParticle

    mParticle Event API

    OpenAPI spec version: 1.0.1
    Contact: support@mparticle.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class ConsentState(object):
    def __init__(self):
        """
        ConsentState - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'ccpa': 'dict',
            'gdpr': 'dict'
        }

        self.attribute_map = {
            'ccpa': 'ccpa',
            'gdpr': 'gdpr'
        }

        self.ccpa = dict()
        self.gdpr = dict()

    @property
    def ccpa(self):
        """
        Gets the ccpa of this CCPAConsentState

        :return The ccpa of this CCPAConsentState
        :rtype dict
        """
        return self._ccpa

    @ccpa.setter
    def ccpa(self, ccpa):
        """
        Sets the ccpa of this Consent State.


        :param ccpa: The ccpa of this Consent State.
        :type: dict
        """

        self._ccpa = ccpa

    @property
    def gdpr(self):
        """
        Gets the gdpr of this GDPRConsentState

        :return The gdpr of this GDPRConsentState
        :rtype dict
        """
        return self._gdpr

    @gdpr.setter
    def gdpr(self, gdpr):
        """
        Sets the gdpr of this Consent State.


        :param gdpr: The gdpr of this Consent State.
        :type: dict 
        """

        self._gdpr = gdpr

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
